language: ruby
rvm: 2.5
dist: trusty
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- 'wget -O ./_data/news.csv $(bundle exec yaml get news-feed -F=_config.yml) || :'
- 'wget -O ./_data/events.csv $(bundle exec yaml get events-feed -F=_config.yml) || :'
- 'wget -O ./_data/profiles.csv $(bundle exec yaml get faculty-feed -F=_config.yml) || :'
- 'wget -O ./_data/media-mentions.csv $(bundle exec yaml get media-mentions-feed -F=_config.yml) || :'
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href --external_only
  --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      secure: OPm6z/wDJo0WkTRCysf6H5eNc2cld2qP8yLopQcJJUszByzFWETX/WdocQY59ei+Cpc7gRBnDWSCFiTt4dR5bz0EnCNwyRkghDjy8z7zF9XIfbTGb06CZFSv1Lxw7rXBY8J/oZhGbuDDwYMmy58aN+hPsgp7dAMd27rEYqsxgG78Fi2k485u3eOFhLai47P9UwJBqaHzCqgfPoyuEV/0A3KFLfn+Zjyr2/jgiWwXkpwORXFfswvhPXA/kzwN1eAfqW1JVr22T0jxKp8bJXFk8QLb8QKbzlZyJgD7fFPHyWk1RLza1Au0h6FT9n04wbPye0xCu+3GckPG6TIV6CQ/gE0jFKJPwTGC8Q7KX2rUihnplDIyPnebQtlwWPO89DLFejSUD4zBjJ6EqlEGBR//npiM/rPvMBpGEUJE5aHgZniNDAJBTwZaZ1i6FBi6e8bxYua7whQwt1yWzV16EY2sz8qwY0qJr+jaX3hE31RsfBTh00aUkTfpZLWX0bcCeEKlJ+OYx8KTdS/opjgbxpw7MVDrjA/LsXSaBWf+9KBoA9nV9Iy2RfRSX8cXi0Le9zvgszJU23XCpaki4PQiPOm192vjuDZ8GX6w7KQOzqHwfJof+g2tX3x4H5yhu/P2cpW1yk1S2toeunX3jayJfDG5nsz5tslJ+MTxW3n0uZuBq+8=
    on_success: always
